version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          name: Restoring Cache - dependencies
          keys:
            - v1-dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      # - run:
      #     name: Test
      #     command: |
      #       bash ./scripts/oneteam/test.sh
      - save_cache:
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
          key: v1-dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "oneteam-patch" ]; then
              echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
              cd draft-js-emoji-plugin
              bash ./oneteam-scripts/npm-publish.sh
            fi
